// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BatteryChargeSource } from "./BatteryChargeSource";
import type { BatteryHealth } from "./BatteryHealth";
import type { BatteryStatus } from "./BatteryStatus";

export type AndroidBatteryInfo = { stats: AndroidBatteryStats, history: Array<number>, };

export type AndroidBatteryStats = { powerSource: BatteryChargeSource, isWeakCharger: boolean, maxChargeCurrentMa: number, maxChargeVoltageMv: number, chargeCounter: number, status: BatteryStatus, health: BatteryHealth, present: boolean, level: number, scale: number, voltage: number, temperature: number, technology: string, };

export type Game = { id: string, title: string, cover: Array<number> | null, vrBackend: string, steamAppId: bigint | null, protonVersion: string | null, commandLine: string | null, totalPlaytimeSec: number, };

export type GameSession = { game: Game, startTimeEpoch: bigint, vrDeviceSerial: string, };
